### ISSUE TITLE
Stop playing sounds when switching instance

### ISSUE THREAD

**Issue by smmarkvard** [IbimsnicesYolo/gmod_instances#1]
Great concept for an addon! Would it be possible to add a feature to stop all currently playing sounds when switching instance

**Comment by Yolo-TM** [comment]
stopping all sounds could be done, but only stopping the sounds from entities of another instance sounds very tricky.

i will think of a solution...

**Comment by smmarkvard** [comment]
I might have a solution to it. still working on it

**Comment by Yolo-TM** [comment]
should be fixed with #5
